[CN-448] Update the tutorial for showing the enhanced use case of WanReplication
hazelcast-guides/hazelcast-platform-operator-wan-replication pull request #2
Opened 2022-09-29 16:13 UTC by cagric0

2022-10-03 10:45 UTC, dzeromski-hazelcast approved these changes

2022-10-06 10:16 UTC, angelasimms requested changes
All changes are minor text updates.

2022-10-06 10:16 UTC, angelasimms commented on docs/modules/ROOT/pages/hazelcast-platform-operator-wan-replication.adoc
> +- Create two Hazelcast map configuration in one of the cluster.
```suggestion
- Create two Hazelcast map configurations on one of the clusters.
```

2022-10-06 10:16 UTC, angelasimms commented on docs/modules/ROOT/pages/hazelcast-platform-operator-wan-replication.adoc
>  - Synchronize map data between two Hazelcast clusters.
```suggestion
- Synchronize map data between the two Hazelcast clusters.
```
Also suggestions for the Before you Begin section below:

Before starting this tutorial, make sure that you have the following:
* A running https://kubernetes.io/[Kubernetes] cluster
* The Kubernetes command-line tool, https://kubernetes.io/docs/tasks/tools/#kubectl[`kubectl`]
* A deployment of Deployed xref:operator:ROOT:index.adoc[Hazelcast Platform Operator]

2022-10-06 10:16 UTC, angelasimms commented on docs/modules/ROOT/pages/hazelcast-platform-operator-wan-replication.adoc
> +. Check the status of the clusters to make sure that it's running.
```suggestion
. Check the status of the clusters to make sure that both clusters are running.
```

2022-10-06 10:16 UTC, angelasimms commented on docs/modules/ROOT/pages/hazelcast-platform-operator-wan-replication.adoc
> +. Create two map in the first cluster.
```suggestion
. Create two maps on the first cluster. In this example, the following maps are created:

- `example-map-1`
- `example-map-2`.
```

2022-10-06 10:16 UTC, angelasimms commented on docs/modules/ROOT/pages/hazelcast-platform-operator-wan-replication.adoc
>  == Step 2. Create WAN Replication Configuration
```suggestion
== Step 2. Create a WAN Replication Configuration
```

2022-10-06 10:16 UTC, angelasimms commented on docs/modules/ROOT/pages/hazelcast-platform-operator-wan-replication.adoc
> +. Create a WAN Replication Configuration.
```suggestion
. Create the configuration for WAN replication:
```

2022-10-06 10:16 UTC, angelasimms commented on docs/modules/ROOT/pages/hazelcast-platform-operator-wan-replication.adoc
> +- Use the first cluster as the source cluster by giving the cluster name as a resource to WAN Replication configuration.
```suggestion
- Use the first cluster as the source cluster by adding its name as a resource in the WAN Replication configuration.
```

2022-10-06 10:16 UTC, angelasimms commented on docs/modules/ROOT/pages/hazelcast-platform-operator-wan-replication.adoc
> +Giving the cluster name as a resource starts the WAN Replication for both of the maps created earlier.
```suggestion
Adding the cluster name as a resource starts WAN replication for both the maps that you created earlier.
```

2022-10-06 10:16 UTC, angelasimms commented on docs/modules/ROOT/pages/hazelcast-platform-operator-wan-replication.adoc
> +- Use the second cluster as the target cluster to receive the WAN Replication events.
```suggestion
- Add the second cluster as the target cluster to receive the WAN Replication events.
```

2022-10-06 10:16 UTC, angelasimms commented on docs/modules/ROOT/pages/hazelcast-platform-operator-wan-replication.adoc
>  Run the following command to configure the replication
```suggestion
Run the following command to apply the configuration.
```

2022-10-06 10:16 UTC, angelasimms commented on docs/modules/ROOT/pages/hazelcast-platform-operator-wan-replication.adoc
> +. Now start the application for each map with their name as a argument to fill the maps.
```suggestion
. Now start the application for each map, using the map name as an argument to fill each map with random entries. If you're reusing the sample code from this tutorial, use the map names `example-map-1` and `example-map-2`.
```

2022-10-06 10:16 UTC, angelasimms commented on docs/modules/ROOT/pages/hazelcast-platform-operator-wan-replication.adoc
> +Map Names -> example-map-1, example-map-2
```suggestion

```
Replaced by suggestion above.

2022-10-06 10:16 UTC, angelasimms commented on docs/modules/ROOT/pages/hazelcast-platform-operator-wan-replication.adoc
> +== Step 3. Verify that the Maps' Entries were Replicated
```suggestion
== Step 3. Verify the Replication of Map Entries
```

2022-10-06 10:16 UTC, angelasimms commented on docs/modules/ROOT/pages/hazelcast-platform-operator-wan-replication.adoc
> +In this step, you verify the sizes of the maps on the second cluster to make sure that they received all the WAN Replication events.
```suggestion
In this step, you'll check the sizes of the maps on the second, target cluster to make sure that WAN replication events have been received.
```

2022-10-06 10:16 UTC, angelasimms commented on docs/modules/ROOT/pages/hazelcast-platform-operator-wan-replication.adoc
>  . Configure the Hazelcast client to connect to the second cluster as you did in <<configure-client, Configure the Hazelcast Client>>.
```suggestion
. Configure the Hazelcast client to connect to the second cluster, as you did in <<configure-client, Configure the Hazelcast Client>>.
```

2022-10-06 10:16 UTC, angelasimms commented on docs/modules/ROOT/pages/hazelcast-platform-operator-wan-replication.adoc
> +. Start the application for each map with their name as a argument to check the map size and see if the WAN Replication was successful.
```suggestion
. Start the application for each map, using the map name as an argument to check the map size, and to check that WAN replication was successful. If you're reusing the sample code from this tutorial, use the map names `example-map-1` and `example-map-2`.
```

2022-10-06 10:16 UTC, angelasimms commented on docs/modules/ROOT/pages/hazelcast-platform-operator-wan-replication.adoc
> +Map Names -> example-map-1, example-map-2
```suggestion

```
Included text in bullet point above.

2022-10-06 10:16 UTC, angelasimms commented on docs/modules/ROOT/pages/hazelcast-platform-operator-wan-replication.adoc
>  == Clean Up
Suggested updates to line 424:

To remove all custom resources and PVCs, run the following commands:

2022-10-06 10:16 UTC, angelasimms commented on clients/go/main.go
> +		fmt.Println("You should pass two argument. The First one is `fill` or `size`. The second one is map name.")
```suggestion
		fmt.Println("You need to pass two arguments. The first argument must be `fill` or `size`. The second argument must be `mapName`.")
```

2022-10-06 10:16 UTC, angelasimms commented on clients/go/main.go
>  		fmt.Println("Wrong argument, you should pass: fill or size")
```suggestion
		fmt.Println("Wrong argument, pass `fill` or `size` instead.")
```

2022-10-06 10:16 UTC, angelasimms commented on clients/java/src/main/java/com/hazelcast/Main.java
> +            System.out.println("You should pass two argument. The First one is `fill` or `size`. The second one is map name.");
```suggestion
            System.out.println("You need to pass two arguments. The first argument must be `fill` or `size`. The second argument must be `mapName`.");
```

2022-10-06 10:16 UTC, angelasimms commented on clients/nodejs/client.js
> +            console.error('You should pass two argument. The First one is `fill` or `size`. The second one is map name.');
```suggestion
            console.error('You need to pass two arguments. The first argument must be `fill` or `size`. The second argument must be `mapName`.');
```

2022-10-06 10:16 UTC, angelasimms commented on clients/python/main.py
> +    print("You should pass two argument. The First one is `fill` or `size`. The second one is map name.")
```suggestion
    print("You need to pass two arguments. The first argument must be `fill` or `size`. The second argument must be `mapName`.")
```

2022-10-10 10:56 UTC, angelasimms requested changes
I think there's some duplication at the start of Step 1.

2022-10-10 10:56 UTC, angelasimms commented on docs/modules/ROOT/pages/hazelcast-platform-operator-wan-replication.adoc
In this step, maybe you could just have the instruction below and remove the instruction on line 31.
```suggestion
. Create a secret with your link:http://trialrequest.hazelcast.com/[Hazelcast Enterprise License].
```

2022-10-10 14:29 UTC, angelasimms approved these changes
All looks good to me. Thanks.

2022-10-10 15:31 UTC, merged